version: '3.9'

services:
  atlantis-obfuscator:
    build: .
    container_name: atlantis-obfuscator
    ports:
      - "10000:10000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 10000
